const fruitsData = {
  Carrot: {
    basePrice: 18,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  Strawberry: {
    basePrice: 14,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  "Chocolate Carrot": {
    basePrice: 16500,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  Blueberry: {
    basePrice: 18,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  "Orange Tulip": {
    basePrice: 767,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  "Red Lollipop": {
    basePrice: 70000,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  Nightshade: {
    basePrice: 2000,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  Tomato: {
    basePrice: 27,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  Corn: {
    basePrice: 36,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  Daffodil: {
    basePrice: 903,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  Raspberry: {
    basePrice: 90,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  "Candy Sunflower": {
    basePrice: 145000,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  Glowshroom: {
    basePrice: 200,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  Mint: {
    basePrice: 6000,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  Apple: {
    basePrice: 248,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  Watermelon: {
    basePrice: 2708,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  Pumpkin: {
    basePrice: 3700,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  Bamboo: {
    basePrice: 3610,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  Papaya: {
    basePrice: 1000,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  Cranberry: {
    basePrice: 1805,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  Durian: {
    basePrice: 4513,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  Moonflower: {
    basePrice: 10000,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  Starfruit: {
    basePrice: 15538,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  Coconut: {
    basePrice: 361,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  Cactus: {
    basePrice: 3068,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  "Dragon Fruit": {
    basePrice: 4287,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  Mango: {
    basePrice: 5866,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  Pineapple: {
    basePrice: 1805,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  Peach: {
    basePrice: 271,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  Pear: {
    basePrice: 500,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  Banana: {
    basePrice: 1579,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  Passionfruit: {
    basePrice: 3204,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  "Easter Egg": {
    basePrice: 4513,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  Eggplant: {
    basePrice: 6769,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  Moonglow: {
    basePrice: 18000,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  "Blood Banana": {
    basePrice: 5415,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  "Moon Melon": {
    basePrice: 16245,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  Grape: {
    basePrice: 7085,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  "Soul Fruit": {
    basePrice: 3000,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  "Cursed Fruit": {
    basePrice: 20000,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  Mushroom: {
    basePrice: 136278,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  Pepper: {
    basePrice: 7220,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  "Venus Fly Trap": {
    basePrice: 17000,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  Lotus: {
    basePrice: 20000,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  "Candy Blossom": {
    basePrice: 93567,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  Cacao: {
    basePrice: 9928,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  "Moon Blossom": {
    basePrice: 45125,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  "Beanstalk": {
    basePrice: 18050,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  "Cherry Blossom": {
    basePrice: 500,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
  "Lemon": {
    basePrice: 500,
    mutations: {
      Moonlit: 2,
      Choco: 2,
      Wet: 2,
      Chilled: 2,
      Bloodlit: 4,
      Frozen: 10,
      Gold: 20,
      Zombified: 25,
      Rainbow: 50,
      Shocked: 50,
      Celetials: 120,
      Disco: 125,
      Plasma: 5,
    },
  },
};

const fruitInput = document.getElementById("fruit-input");
const mutationSelect = document.getElementById("mutation-select");
const resultsDiv = document.getElementById("results");
const resultsList = document.getElementById("results-list");
const form = document.getElementById("mutation-form");

const allFruits = Object.keys(fruitsData);

// Populate datalist options on load
window.addEventListener("DOMContentLoaded", () => {
  function populateFruitDatalist(fruits) {
    const fruitList = document.getElementById("fruit-list");
    fruitList.innerHTML = "";
    fruits.forEach((fruit) => {
      const option = document.createElement("option");
      option.value = fruit;
      fruitList.appendChild(option);
    });
  }

  populateFruitDatalist(allFruits);
});

// Update mutation checkboxes based on selected fruit input
fruitInput.addEventListener("input", () => {
  const mutationCheckboxes = document.getElementById("mutation-checkboxes");
  mutationCheckboxes.innerHTML = "";
  const selectedFruit = fruitInput.value;
  if (selectedFruit && fruitsData[selectedFruit]) {
    const mutations = fruitsData[selectedFruit].mutations;
    for (const mutation in mutations) {
      const label = document.createElement("label");
      label.style.marginRight = "10px";
      const checkbox = document.createElement("input");
      checkbox.type = "checkbox";
      checkbox.name = "mutation";
      checkbox.value = mutation;
      label.appendChild(checkbox);
      label.appendChild(document.createTextNode(" " + mutation));
      mutationCheckboxes.appendChild(label);
    }
  }
  resultsDiv.style.display = "none";
  resultsList.innerHTML = "";
});

// Compute mutation on form submit
form.addEventListener("submit", (e) => {
  e.preventDefault();
  const selectedFruit = fruitInput.value;
  const mutationCheckboxes = document.querySelectorAll(
    '#mutation-checkboxes input[type="checkbox"]:checked'
  );
  const selectedMutations = Array.from(mutationCheckboxes).map(
    (checkbox) => checkbox.value
  );

  if (!selectedFruit || !fruitsData[selectedFruit] || selectedMutations.length === 0) {
    alert("Please select a valid fruit and at least one mutation.");
    return;
  }

  const basePrice = fruitsData[selectedFruit].basePrice;

  // Calculate product of all selected mutation multipliers
  let totalMultiplier = 1;
  selectedMutations.forEach((mutation) => {
    totalMultiplier *= fruitsData[selectedFruit].mutations[mutation];
  });

  const mutatedValue = basePrice * totalMultiplier;

  resultsList.innerHTML = "";
  const resultItem = document.createElement("div");
  resultItem.className = "result-item";
  resultItem.textContent = `${selectedFruit} with 
  mutations "${selectedMutations.join(
    ", "
  )}" = ${mutatedValue.toLocaleString()} sheckles`;
  resultsList.appendChild(resultItem);
  resultsDiv.style.display = "block";
});
